shamefullyHoist: true

packages:
  - playground

catalog:
  "@nuxt/icon": ^2.0.0
  "@nuxtjs/color-mode": ^3.5.2
  "@primeuix/themes": ^1.2.3
  "@primevue/nuxt-module": ^4.3.9
  "@types/node": ^24.5.1
  "@unocss/nuxt": ^66.5.1
  "@vueuse/core": ^13.9.0
  "@vueuse/nuxt": ^13.9.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/stylelint-config": ^0.3.3
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.3
  eslint: ^9.35.0
  nuxt: ^4.1.2
  primevue: ^4.3.9
  shiki: ^3.12.2
  stylelint: ^16.24.0
  tsdown: ^0.15.2
  unocss: ^66.5.1
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-router: ^4.5.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - rolldown
