shamefullyHoist: true

packages:
  - playground

catalog:
  "@antfu/eslint-config": ^4.13.2
  "@nuxt/icon": ^1.13.0
  "@nuxtjs/color-mode": ^3.5.2
  "@primeuix/themes": ^1.1.1
  "@primevue/nuxt-module": ^4.3.4
  "@types/node": ^22.15.21
  "@unocss/nuxt": ^66.1.2
  "@vueuse/core": ^13.2.0
  "@vueuse/nuxt": ^13.2.0
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/stylelint-config": ^0.3.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.1
  eslint: ^9.27.0
  nuxt: ^3.17.4
  primevue: ^4.3.4
  shiki: ^3.4.2
  stylelint: ^16.19.1
  tsdown: ^0.12.2
  unocss: ^66.1.2
  vitest: ^3.1.4
  vue: ^3.5.14
  vue-router: ^4.5.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - rolldown
  - unrs-resolver
  - vue-demi
