packages:
  - playground

catalog:
  "@antfu/eslint-config": ^4.12.0
  "@nuxt/icon": ^1.12.0
  "@nuxtjs/color-mode": ^3.5.2
  "@types/node": ^22.15.3
  "@unocss/nuxt": ^66.0.0
  "@vueuse/core": ^13.1.0
  "@vueuse/nuxt": ^13.1.0
  "@zinkawaii/eslint-config": ^0.2.3
  "@zinkawaii/stylelint-config": ^0.3.1
  "@zinkawaii/tsconfig": ^0.0.1
  bumpp: ^10.1.0
  eslint: ^9.25.1
  nuxt: ^3.17.0
  radix-vue: ^1.9.17
  shiki: ^3.3.0
  stylelint: ^16.19.1
  tsdown: ^0.10.0
  unocss: ^66.0.0
  vitest: ^3.1.2
  vue: ^3.5.13
  vue-router: ^4.5.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - rolldown
  - unrs-resolver
  - vue-demi