shamefullyHoist: true

packages:
  - playground

catalog:
  "@nuxt/icon": ^2.1.0
  "@nuxtjs/color-mode": ^3.5.2
  "@primeuix/themes": ^1.2.5
  "@primevue/nuxt-module": ^4.4.1
  "@types/node": ^24.9.2
  "@unocss/nuxt": ^66.5.4
  "@vueuse/core": ^14.0.0
  "@vueuse/nuxt": ^14.0.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/stylelint-config": ^0.3.3
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.3.1
  eslint: ^9.39.0
  nuxt: ^4.2.0
  primevue: ^4.4.1
  shiki: ^3.14.0
  stylelint: ^16.25.0
  tsdown: ^0.15.12
  unocss: ^66.5.4
  vitest: ^4.0.6
  vue: ^3.5.22
  vue-router: ^4.6.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
